import { createLogger, defineConfig, loadEnv, Plugin } from 'vite';
import { viteStaticCopy } from 'vite-plugin-static-copy';
import solidPlugin from 'vite-plugin-solid';
import { builtinModules as builtins } from 'node:module';
import path from 'path';
import * as fsp from 'fs/promises';
import { TEXT_FILES, textLoader } from './tools/text-loader.ts';



const banner = `
/*!
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository https://github.com/pan4ratte/obsidian-pandoc-gui .
*/
`;


export default defineConfig(({ mode }) => {
  const prod = mode === 'production';

  const { OUT_DIR } = loadEnv(mode, process.cwd(), ['OUT_']);

  // Defaults to the repository root, so the repo itself is a ready-to-load plugin folder.
  const outDir = path.resolve(process.cwd(), OUT_DIR ? OUT_DIR : '.');
  // manifest.json and styles.css already live in the root, copying them onto
  // themselves would fail. They are only copied when building elsewhere.
  const copyAssets = outDir !== path.resolve(process.cwd());

  return {
    // Vite warns about `outDir` being the root, which is intended here (`emptyOutDir` is off).
    customLogger: silence(/build\.outDir must not be the same directory of root/),
    plugins: [
      // Solid delegates `click` and friends to a single listener on the document the plugin was loaded in.
      // Obsidian opens a modal in `activeWindow`, so settings and dialogs raised from a popout live in that
      // window's document instead, where the listener is not — every handler dies while natively bound ones
      // (`change` on a dropdown) go on working. Bound to the element, they follow it into any window.
      solidPlugin({ solid: { delegateEvents: false } }),
      copyAssets ? viteStaticCopy({
        targets: [
          { src: 'manifest.json', dest: '.' },
          { src: 'styles.css', dest: '.' },
        ]
      }) : undefined,
      textLoader(TEXT_FILES), // src/resources.ts, src/lang/helpers.ts
      stubImportMetaUrl(/@myriaddreamin[\\/]/),
      prod ? undefined : inject(['src/hmr.ts']),
    ],
    build: {
      lib: {
        entry: 'src/main.ts',
        name: 'main',
        fileName: () => 'main.js',
        formats: ['cjs'],
      },
      minify: prod,
      sourcemap: prod ? false : 'inline',
      emptyOutDir: false,
      outDir,
      rollupOptions: {
        output: {
          exports: 'named',
          // `banner` is prepended before minification, which drops the comment.
          postBanner: banner,
          // Node and electron are reached by dynamic import, so that a phone — which has neither — can still load the
          // plugin. Left as a native `import()`, the renderer refuses a bare specifier it has no resolver for
          // ("Failed to resolve module specifier 'electron'"); this emits `require()` for them instead, which is how
          // the same modules were reached when they were imported at the top of a file.
          dynamicImportInCjs: false,
        },
        external: [
          'obsidian',
          'electron',
          '@codemirror/autocomplete',
          '@codemirror/closebrackets',
          '@codemirror/collab',
          '@codemirror/commands',
          '@codemirror/comment',
          '@codemirror/fold',
          '@codemirror/gutter',
          '@codemirror/highlight',
          '@codemirror/history',
          '@codemirror/language',
          '@codemirror/lint',
          '@codemirror/matchbrackets',
          '@codemirror/panel',
          '@codemirror/rangeset',
          '@codemirror/rectangular-selection',
          '@codemirror/search',
          '@codemirror/state',
          '@codemirror/stream-parser',
          '@codemirror/text',
          '@codemirror/tooltip',
          '@codemirror/view',
          '@lezer/common',
          '@lezer/highlight',
          '@lezer/lr',
          ...builtins
        ],
      },
    }
  };
});


const silence = (pattern: RegExp) => {
  const logger = createLogger();
  const { warn, warnOnce } = logger;
  logger.warn = (msg, options) => {
    if (!pattern.test(msg)) {
      warn.call(logger, msg, options);
    }
  };
  logger.warnOnce = (msg, options) => {
    if (!pattern.test(msg)) {
      warnOnce.call(logger, msg, options);
    }
  };
  return logger;
};


/**
 * Typst's wasm-bindgen wrappers end in a branch that fetches the `.wasm` beside themselves, named against
 * `import.meta.url`. The plugin never takes it — the compiler is handed the binary the vault has on disk — and a cjs
 * bundle has no `import.meta` to give it, so rolldown replaces the whole expression with `{}` and warns that it did.
 * Written out here instead, which leaves the dead branch dead and the build quiet.
 */
const stubImportMetaUrl = (test: RegExp): Plugin => ({
  name: 'stub-import-meta-url',
  enforce: 'pre',
  transform(code, id) {
    if (test.test(id) && code.includes('import.meta.url')) {
      return { code: code.replaceAll('import.meta.url', 'undefined'), map: null };
    }
  },
});


const inject = (files: string[]): Plugin => {
  if (files && files.length > 0) {
    return {
      name: 'inject-code',
      async load(this, id) {
        const info = this.getModuleInfo(id);
        if (info.isEntry) {
          const code = await fsp.readFile(id, 'utf-8');
          const { relative, dirname, basename, extname, join } = path;
          const dir = dirname(id);
          const inject_code = files
            .map(v => relative(dir, v))
            .map(p => join('./', basename(p, extname(p))))
            .map(p => `import './${p}'`).join(';');
          return `
          ${inject_code};
          ${code}
          `;
        }
      },
    };
  }
};